DROP DATABASE IF EXISTS tracker_db;
CREATE DATABASE IF EXISTS tracker_db;

\c tracker_db;

CREATE TABLE department (
id SERIAL PRIMARY KEY
name VARCHAR(30) NOT NULL
);

CREATE TABLE role (
id SERIAL PRIMARY KEY
title VARCHAR(30) NOT NULL
salary DECIMAL(10,2) NOT NULL
FOREIGN KEY (department_id)
REFERENCES department(id)
ON DELETE SET NULL
)

CREATE TABLE employee (
id SERIAL PRIMARY KEY
first_name VARCHAR(30) NOT NULL
last_name VARCHAR(30) NOT NULL
FOREIGN KEY (role_id)
REFERENCES role(id)
ON DELETE SET NULL
);